# Generated by Django 4.2.4 on 2023-08-24 12:06

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, max_length=150, populate_from='title', unique=True),
        ),
    ]
