# Generated by Django 4.2.4 on 2023-08-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about_heading", models.CharField(max_length=25)),
                ("about_description", models.TextField(max_length=255)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "About",
            },
        ),
    ]
